### PR TITLE
catkinize packages

### PR DESCRIPTION
**Pull request by k-okada**
catkinized version of pr2_navigation:groovy-devel, this is not tested on the robot, just confirm that it is able to compile

### CODE REVIEW

**Comment by UltronDestroyer** [comment]
Hi ko-kada,

I'm going to confirm it compiles. I see you also replaced the library calls with the updated hydro calls. Awesome.

Will test this on the robot sometime in the future.

**Comment by UltronDestroyer** [comment]
This compiles if you have these additional packages from source (they haven't been released yet)
https://github.com/PR2/pr2_apps/tree/hydro-devel/pr2_teleop
https://github.com/PR2/pr2_common_actions/tree/hydro-devel/joint_trajectory_generator
https://github.com/PR2/pr2_common_actions/tree/hydro-devel/joint_trajectory_action_tools

and these additional packages from debian:
ros-hydro-laser-filters
ros-hydro-pr2-machine
ros-hydro-pr2-controllers

Strong work @k-okada & @airballking

**Comment by k-okada** [comment]
hi, Thanks for merging!!!

as for packages from sources,  I have already catkinized packages required for this patch at 
https://github.com/PR2/pr2_common_actions/pull/27, so hope that is also merged soon.

I also hope to release (blooming) latest pr2_app and pr2_common_actions. I think if you run bloom on these packages, it works and bloom just skip non-catkinized package so I think it is ok, but do we need to catkinize all packages before release?

**Comment by UltronDestroyer** [comment]
(Edit) after second thought, it's probably not necessary to wait. The only concern I have is when people go to use it and see bugs in some of the packages, they might be a bit turned off.

**Comment by airballking** [comment]
Thanks! :)

I stopped (pursuing catkinizing the downstream dependencies) when I saw the rabbit-hole related to the pr2-planning plugins: That collection of packages appeared too entangled (and deprecated) to me, and I couldn't figure out where to start --a real bonafide spaghetti problem. If any of you can point out a set of packages to start with (for catkinization), I'd be happy to further give a helping hand.

**Comment by UltronDestroyer** [comment]
I would like to point you in a good direction, but what does pr2-planning plugins refer to?

**Pull request merged**
