### PR TITLE
fix typo in catkin_INCLUDE_DIRS

### LINKED ISSUE #33: semantic_point_annotater fails to build on Kinetic
It looks to be missing a dependency.

http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__semantic_point_annotator__ubuntu_xenial_amd64__binary/14/console
```
fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2     -DDISABLE_LIBUSB-1.0 -fPIC -o CMakeFiles/sac_inc_ground_removal_node.dir/src/sac_inc_ground_removal_standalone.cpp.o -c /tmp/binarydeb/ros-kinetic-semantic-point-annotator-0.1.27/src/sac_inc_ground_removal_standalone.cpp
<command-line>:0:15: warning: missing whitespace after the macro name
/tmp/binarydeb/ros-kinetic-semantic-point-annotator-0.1.27/src/sac_inc_ground_removal_standalone.cpp:43:21: fatal error: ros/ros.h: No such file or directory
compilation terminated.
```

### PR DESCRIPTION
**Pull request by v4hn**
Fixes #33

### CODE REVIEW

**Review by k-okada — APPROVED** [review]
thanks!

**Comment by k-okada** [comment]
@v4hn will you release this package to close https://github.com/ros/rosdistro/pull/17621 ?

**Comment by v4hn** [comment]
> will you release this package

Could you please do that? I don't have resources for that at the moment.

**Comment by k-okada** [comment]
ok.

--
◉ Kei Okada


2018-04-26 22:05 GMT+09:00 Michael Görner <notifications@github.com>:

**Pull request merged**
